// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFLi-pmIiMgvCCSmK7MhyYCmMgxwcLLYg',
    appId: '1:1021868034972:web:e0f5957e7a3cf281b79659',
    messagingSenderId: '1021868034972',
    projectId: 'i-bin-19309',
    authDomain: 'i-bin-19309.firebaseapp.com',
    storageBucket: 'i-bin-19309.appspot.com',
    measurementId: 'G-VYT2WQ63E0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjTwuzGJHGrkDU9XOa2kxObAIJo3PObY4',
    appId: '1:1021868034972:android:e3c8a3d21d799072b79659',
    messagingSenderId: '1021868034972',
    projectId: 'i-bin-19309',
    storageBucket: 'i-bin-19309.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIVcGKZcYbaHFgRJmOfEEx8_64_o3Kcpc',
    appId: '1:1021868034972:ios:87687659be7f486cb79659',
    messagingSenderId: '1021868034972',
    projectId: 'i-bin-19309',
    storageBucket: 'i-bin-19309.appspot.com',
    iosBundleId: 'com.example.iBin1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIVcGKZcYbaHFgRJmOfEEx8_64_o3Kcpc',
    appId: '1:1021868034972:ios:901f2250e6ae642cb79659',
    messagingSenderId: '1021868034972',
    projectId: 'i-bin-19309',
    storageBucket: 'i-bin-19309.appspot.com',
    iosBundleId: 'com.example.iBin1.RunnerTests',
  );
}
